### ISSUE TITLE
Design fortune telling page

### ISSUE THREAD

**Issue by yyygrace** [the132Debuggers/cse110-sp23-the132Debuggers#45]
Design the page which contains the fortune telling component.

- The layout consists of:
  - A text bar for users to input a question
  - An image of a character representing the house
- Include any font/colors in the mood board frame for the corresponding house
- Create styles for each house:
- [x] Gryffindor
- [x] Slytherin
- [x] Ravenclaw
- [x] Hufflepuff

**Comment by hhundhausen** [comment]
Completed.
